### ISSUE TITLE
Not visible on RecycleView

### ISSUE THREAD

**Issue by llisas** [zurche/plain-pie#12]
Hello , thanks for your librery.

I am trying to add a plain-pie on an RecycleView but is  not is not showed after run the proyect either on the xml preview. 

the xml code for a recycleView item  is :
```
<?xml version="1.0" encoding="utf-8"?>

<layout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    xmlns:plainpie="http://schemas.android.com/tools">

    <android.support.v7.widget.CardView
        android:id="@+id/card_tech"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginTop="@dimen/standard_margin"
        android:layout_marginLeft="@dimen/standard_margin"
        android:layout_marginRight="@dimen/standard_margin"
        card_view:cardCornerRadius="4dp"
        card_view:cardBackgroundColor="@color/primary_light">


        <az.plainpie.PieView
            android:id="@+id/pieView"
            android:layout_marginTop="10dp"
            android:layout_width="200dp"
            android:layout_height="200dp"
            plainpie:percentage="75"
            plainpie:percentage_size="70"
            plainpie:inner_text_visibility="true"
            android:layout_gravity="center"/>

    </android.support.v7.widget.CardView>


</layout>
```

**Comment by ssaxena01** [comment]
I see the same problem. A black circle appears on the cardview.

**Comment by zurche** [comment]
Hi @llisas and @ssaxena01 after a long time I've revised the project and checked this issue.

I tested the approach you took and was able to implement a RecylcerView with items that had a CardView in a branch of this project: https://github.com/zurche/plain-pie/tree/recycler_view_issue

You both may review the implementation I made since I can see it working as expected:
![sc_1](https://user-images.githubusercontent.com/15671525/36646139-7267f3c2-1a52-11e8-83f8-a439c85949ac.png)

One thing I noticed though is that you were not using the `inner_pie_padding` attribute of the PieView which lead to an invisible progress bar, for that reason I'll improve the code of the lib to have a default value unless specified by xml to avoid it in the future.

Thanks to both of you for taking the time into reporting this issue.
